#!/bin/bash
# first argument is type of dataset we're going to generate
E_BADARGS=65

if [ $# -ne 1 ]
then
    echo "Usage: `basename $0` {size}"
    exit $E_BADARGS
fi
SIZE=$1
re='^[0-9]+$'
if ! [[ $SIZE =~ $re ]] ; then
  echo "error: given size is not a number" >&2; exit 1
fi
PWD="$(pwd)"
CMD="impossible"
if [[ ! -f "$PWD/$CMD" ]]; then
  echo "$PWD/$CMD does not exist"
  exit 1
fi

NAME="impossible-${SIZE}n"
FILE="${NAME}.arff"
DATA="${NAME}.dat"
make
EXEC="./${CMD} -n $SIZE -b 0.1"
bash -c "${EXEC}"
if [[ ! -f $DATA ]]; then
  echo "data set ${DATA} was not found"
  exit 1
fi
tab2csv $DATA $FILE

cat <<EOF > "/tmp/out"
% generated dataset with the 'impossible' generator
% using:
%
%  $EXEC
%
@RELATION $NAME

@ATTRIBUTE x REAL
@ATTRIBUTE y REAL
@ATTRIBUTE class {0,1}

@DATA
EOF
cat "$FILE" >> /tmp/out && mv /tmp/out $FILE
if [[ -d ~/dev/clustering-benchmark ]]; then
  cp $FILE ~/dev/clustering-benchmark/src/main/resources/datasets/artificial/$FILE
  cd ~/dev/clustering-benchmark
  mvn install -DskipTests
fi
